### ISSUE TITLE
Support futures::AsyncRead being body for multipart upload API

### ISSUE THREAD

**Issue by yiwu-arbug** [EmbarkStudios/tame-gcs#17]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
It looks to me the body of a multipart upload can only be a `io::Read`, which does not support async reading like the `future::AsyncRead`. Do you consider supporting it? Thanks.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by Jake-Shadle** [comment]
Yes, we could definitely add that. Probably feature gated behind a futures flag though so that futures/async is not required if you don't want it.
