### ISSUE TITLE
Support custom endpoints

### ISSUE THREAD

**Issue by kennytm** [EmbarkStudios/tame-gcs#21]
**Is your feature request related to a problem? Please describe.**

tame-gcs currently hardcodes the request URLs 

https://github.com/EmbarkStudios/tame-gcs/blob/57dde1086e4a9ccbaa7921e0fddc90a26748ed74/src/v1/objects/insert.rs#L387

https://github.com/EmbarkStudios/tame-gcs/blob/57dde1086e4a9ccbaa7921e0fddc90a26748ed74/src/v1/objects/get.rs#L63

If we want to use [change the endpoints](https://cloud.google.com/storage/docs/request-endpoints) to use other GCS-compatible services e.g. [fake-gcs-server](https://github.com/fsouza/fake-gcs-server), we will need to manually replace the URLs in the generated `http::Request`, which is awkward.

Note that the official GCS libraries in all other languages support providing custom endpoints:

* [C++](https://googleapis.dev/cpp/google-cloud-storage/latest/classgoogle_1_1cloud_1_1storage_1_1v1_1_1ClientOptions.html#ad1041d59628865860aa3ae081c2133ec)
* [C#](https://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Storage.V1/api/Google.Api.Gax.Rest.ClientBuilderBase-1.html#Google_Api_Gax_Rest_ClientBuilderBase_1_BaseUri)
* [Go](https://pkg.go.dev/google.golang.org/api/option?tab=doc#WithEndpoint)
* [Java](https://googleapis.dev/java/google-cloud-clients/latest/com/google/cloud/ServiceOptions.Builder.html#setHost-java.lang.String-)
* [NodeJS](https://github.com/googleapis/nodejs-storage/blob/f72082d39608a0d23dd3c3b89528346634905cf6/src/storage.ts#L52-L56)
* [Python](https://googleapis.dev/python/google-api-core/latest/client_options.html#google.api_core.client_options.ClientOptions)
* [Ruby](https://googleapis.dev/ruby/google-cloud-storage/latest/Google/Cloud/Storage.html#new-class_method)

**Describe the solution you'd like**

Have an API specifying which endpoint to use.

**Describe alternatives you've considered**

**Additional context**

**Comment by Jake-Shadle** [comment]
Resolved by #59
