### ISSUE TITLE
Support resumable upload

### ISSUE THREAD

**Issue by kennytm** [EmbarkStudios/tame-gcs#24]
**Is your feature request related to a problem? Please describe.**

Currently `tame-gcs` only exposed API for uploading a file atomically (`insert_multipart` and `insert_simple`). 

For huge files it is more robust to use [resumable upload](https://cloud.google.com/storage/docs/performing-resumable-uploads) (insert with `uploadType=resumable`) to upload the file in chunks.

**Describe the solution you'd like**

Add a method to support the resumable upload API.

**Describe alternatives you've considered**

Add a method to support the [compose](https://cloud.google.com/storage/docs/json_api/v1/objects/compose) API (or both).

**Additional context**

**Comment by shikhar** [comment]
I think this can be closed now, with 0.11.3 released!

**Comment by Jake-Shadle** [comment]
Closed by #54
