### ISSUE TITLE
Make all enum Copyable?

### ISSUE THREAD

**Issue by hbina** [EmbarkStudios/tame-gcs#30]
**Is your feature request related to a problem? Please describe.**
Its very annoying to manually implement a copy constructor for `enum`.
Some of  these are very large.

**Describe the solution you'd like**
Copies of cheap enums should be easy to make.

**Describe alternatives you've considered**
Creating a large functions that are error prone.

**Additional context**

**Comment by kennytm** [comment]
Also `Debug` and `Eq` please 🙂
